---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gowhoami-v1
spec:
  replicas: 1
  selector:
    app: gowhoami-v1
  template:
    metadata:
      labels:
        app: gowhoami-v1
    spec:
      containers:
      - image: jonazz/gowhoami:0.0.1
        imagePullPolicy: Always
        args:
          - -d=false
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        name: gowhoami
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            # Path to probe; should be cheap, but representative of typical behavior
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gowhoami
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: gowhoami-v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gowhoami
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: gowhoami
          servicePort: 8080
        path: /api/gowhoami
